query Estimates($status: String) {
  estimates(status: $status) {
  id
  createdAt
  updatedAt
  job {
    id
    createdAt
    updatedAt
    client {
      id
      createdAt
      updatedAt
      name
      email
      phone
      address1
      address2
      city
      state
      zipCode
      notes
      locationLatitude
      locationLongitude
      pk
      address1
      address2
      zipCode
      locationLatitude
      locationLongitude
    }
    title
    description
    status
    scheduledDate
    dueDate
    invoices {
      id
      createdAt
      updatedAt
      date
      dueDate
      status
      total
      applyTaxes
      lineItems {
        id
        createdAt
        updatedAt
        title
        description
        price
        type
        taxType
      }
    }
  }
  date
  status
  total
  applyTaxes
  lineItems {
    id
    createdAt
    updatedAt
    title
    description
    price
    type
    taxType
  }
  }
}