mutation AcceptInvitation($input: InvitationResponseInput!) {
  acceptInvitation(input: $input) {
  success
  message
  account {
    id
    name
    owner {
      id
      email
      firstName
      lastName
    }
    isActive
    subscriptionPlan {
      id
      name
      description
      price
      currency
      period
      trialPeriodDays
      isActive
      maxJobs
      maxClients
      maxTeamMembers
      createdAt
      updatedAt
    }
    subscriptionEndDate
    members {
      isAdmin
      id
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
  }
}