mutation UpdateBusinessProfile($input: BusinessProfileInput!) {
  updateBusinessProfile(input: $input) {
  businessProfile {
    pk
    id
    createdAt
    updatedAt
    name
    email
    phone
    website
    logo
    address1
    address2
    city
    state
    zipCode
    taxServiceType
    account {
      id
      name
      owner {
        id
        email
        firstName
        lastName
      }
      isActive
      subscriptionPlan {
        id
        name
        description
        price
        currency
        period
        trialPeriodDays
        isActive
        maxJobs
        maxClients
        maxTeamMembers
        createdAt
        updatedAt
      }
      subscriptionEndDate
      members {
        isAdmin
        id
        createdAt
        updatedAt
      }
      createdAt
      updatedAt
    }
  }
  success
  message
  }
}